name: Max Dobeck
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title

kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - rouge
  - jekyll-sitemap
  - jekyll-seo-tag

